CREATE TABLE convidados (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome_completo VARCHAR(255) NOT NULL,
    nome_preferido VARCHAR(255),
    endereco VARCHAR(255) NOT NULL,
    numero VARCHAR(10),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255) NOT NULL,
    estado CHAR(2) NOT NULL,
    cep CHAR(9) NOT NULL,
    sexo CHAR(1),
    email VARCHAR(255) NOT NULL,
    data_nascimento DATE,
    cpf VARCHAR(14),
    rg VARCHAR(20),
    contato_emergencia_nome VARCHAR(255),
    contato_emergencia_telefone VARCHAR(20),
    mercado VARCHAR(255),
    gerencia_vendas VARCHAR(255),
    regiao_estrategica VARCHAR(255),
    setor VARCHAR(255),
    meio_transporte VARCHAR(255),
    aeroporto_embarque VARCHAR(255),
    cor_base_natura_una VARCHAR(255),
    cor_base_corretivo_avon VARCHAR(255),
    tipo_pele VARCHAR(255),
    tipo_cabelo VARCHAR(255),
    telefone_contato VARCHAR(20),
    whatsapp_contato VARCHAR(20),
    tamanho_camiseta VARCHAR(10),
    tamanho_calcado VARCHAR(10),
    eh_pcd VARCHAR(255),
    pcd_descricao VARCHAR(255),
    alergia_restricao_alimentar VARCHAR(255),
    alergia_restricao_alimentar_descricao VARCHAR(255),
    alergia_restricao_medicamento VARCHAR(255),
    alergia_restricao_medicamento_descricao VARCHAR(255),
    esta_gravida VARCHAR(255),
    semanas_gravidez VARCHAR(255)
);


